// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(beebeeb_uniffiFFI)
import beebeeb_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_beebeeb_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_beebeeb_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBeebeebUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Stateful decoder handle.
 */
public protocol ConstellationDecoderHandleProtocol: AnyObject, Sendable {
    
    func framesIngested()  -> UInt32
    
    /**
     * Feed one observed frame. Returns the recovered payload when the
     * codeword is complete, otherwise `None`.
     */
    func ingestFrame(observations: [ObservedNodeDto])  -> ConstellationPayloadDto?
    
    func progress()  -> Float
    
    func reset() 
    
    func shardsCollected()  -> UInt32
    
}
/**
 * Stateful decoder handle.
 */
open class ConstellationDecoderHandle: ConstellationDecoderHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_beebeeb_uniffi_fn_clone_constellationdecoderhandle(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_beebeeb_uniffi_fn_constructor_constellationdecoderhandle_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_beebeeb_uniffi_fn_free_constellationdecoderhandle(handle, $0) }
    }

    

    
open func framesIngested() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_beebeeb_uniffi_fn_method_constellationdecoderhandle_frames_ingested(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Feed one observed frame. Returns the recovered payload when the
     * codeword is complete, otherwise `None`.
     */
open func ingestFrame(observations: [ObservedNodeDto]) -> ConstellationPayloadDto?  {
    return try!  FfiConverterOptionTypeConstellationPayloadDto.lift(try! rustCall() {
    uniffi_beebeeb_uniffi_fn_method_constellationdecoderhandle_ingest_frame(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeObservedNodeDto.lower(observations),$0
    )
})
}
    
open func progress() -> Float  {
    return try!  FfiConverterFloat.lift(try! rustCall() {
    uniffi_beebeeb_uniffi_fn_method_constellationdecoderhandle_progress(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func reset()  {try! rustCall() {
    uniffi_beebeeb_uniffi_fn_method_constellationdecoderhandle_reset(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func shardsCollected() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_beebeeb_uniffi_fn_method_constellationdecoderhandle_shards_collected(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConstellationDecoderHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ConstellationDecoderHandle

    public static func lift(_ handle: UInt64) throws -> ConstellationDecoderHandle {
        return ConstellationDecoderHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ConstellationDecoderHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConstellationDecoderHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ConstellationDecoderHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationDecoderHandle_lift(_ handle: UInt64) throws -> ConstellationDecoderHandle {
    return try FfiConverterTypeConstellationDecoderHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationDecoderHandle_lower(_ value: ConstellationDecoderHandle) -> UInt64 {
    return FfiConverterTypeConstellationDecoderHandle.lower(value)
}






/**
 * Opaque handle to a FileKey. Created via `MasterKeyHandle::derive_file_key`.
 */
public protocol FileKeyHandleProtocol: AnyObject, Sendable {
    
    func decryptChunk(nonce: Data, ciphertext: Data) throws  -> Data
    
    func decryptMetadata(nonce: Data, ciphertext: Data) throws  -> String
    
    func encryptChunk(plaintext: Data) throws  -> EncryptedData
    
    func encryptMetadata(metadata: String) throws  -> EncryptedData
    
}
/**
 * Opaque handle to a FileKey. Created via `MasterKeyHandle::derive_file_key`.
 */
open class FileKeyHandle: FileKeyHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_beebeeb_uniffi_fn_clone_filekeyhandle(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_beebeeb_uniffi_fn_free_filekeyhandle(handle, $0) }
    }

    

    
open func decryptChunk(nonce: Data, ciphertext: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_filekeyhandle_decrypt_chunk(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(nonce),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
    
open func decryptMetadata(nonce: Data, ciphertext: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_filekeyhandle_decrypt_metadata(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(nonce),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
    
open func encryptChunk(plaintext: Data)throws  -> EncryptedData  {
    return try  FfiConverterTypeEncryptedData_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_filekeyhandle_encrypt_chunk(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(plaintext),$0
    )
})
}
    
open func encryptMetadata(metadata: String)throws  -> EncryptedData  {
    return try  FfiConverterTypeEncryptedData_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_filekeyhandle_encrypt_metadata(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(metadata),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFileKeyHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FileKeyHandle

    public static func lift(_ handle: UInt64) throws -> FileKeyHandle {
        return FileKeyHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FileKeyHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FileKeyHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FileKeyHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileKeyHandle_lift(_ handle: UInt64) throws -> FileKeyHandle {
    return try FfiConverterTypeFileKeyHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileKeyHandle_lower(_ value: FileKeyHandle) -> UInt64 {
    return FfiConverterTypeFileKeyHandle.lower(value)
}






/**
 * Opaque handle to a MasterKey. The key bytes never leave Rust except via
 * `export_for_keychain`, which is only called once to persist to the OS keychain.
 */
public protocol MasterKeyHandleProtocol: AnyObject, Sendable {
    
    /**
     * Compute the recovery-check value (stored server-side to verify the phrase).
     */
    func computeRecoveryCheck() throws  -> Data
    
    /**
     * Decrypt a `name_encrypted` envelope using the handle's master key.
     */
    func decryptName(fileId: String, nameEncrypted: String) throws  -> String
    
    /**
     * Decrypt a `name_encrypted` envelope and return both filename and MIME type.
     */
    func decryptNameWithMime(fileId: String, nameEncrypted: String) throws  -> DecryptedNameWithMime
    
    /**
     * Derive a FileKeyHandle for the given file ID.
     */
    func deriveFileKey(fileId: Data) throws  -> FileKeyHandle
    
    /**
     * Derive the X25519 secret scalar from the master key. Returns 32 bytes.
     */
    func deriveX25519Private() throws  -> Data
    
    /**
     * Encrypt a filename + optional MIME type using the handle's master key.
     */
    func encryptName(fileId: String, filename: String, mimeType: String?) throws  -> String
    
    /**
     * Export the raw 32-byte key for writing to the OS keychain.
     * Only call this once at account setup; never log or transmit the result.
     */
    func exportForKeychain() throws  -> Data
    
}
/**
 * Opaque handle to a MasterKey. The key bytes never leave Rust except via
 * `export_for_keychain`, which is only called once to persist to the OS keychain.
 */
open class MasterKeyHandle: MasterKeyHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_beebeeb_uniffi_fn_clone_masterkeyhandle(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_beebeeb_uniffi_fn_free_masterkeyhandle(handle, $0) }
    }

    
    /**
     * Reconstruct a MasterKeyHandle from 32 raw bytes read from the OS keychain.
     */
public static func fromKeychainBytes(bytes: Data)throws  -> MasterKeyHandle  {
    return try  FfiConverterTypeMasterKeyHandle_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_constructor_masterkeyhandle_from_keychain_bytes(
        FfiConverterData.lower(bytes),$0
    )
})
}
    
    /**
     * Reconstruct a MasterKeyHandle from a 12-word BIP39 recovery phrase.
     */
public static func fromRecoveryPhrase(phrase: String)throws  -> MasterKeyHandle  {
    return try  FfiConverterTypeMasterKeyHandle_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_constructor_masterkeyhandle_from_recovery_phrase(
        FfiConverterString.lower(phrase),$0
    )
})
}
    

    
    /**
     * Compute the recovery-check value (stored server-side to verify the phrase).
     */
open func computeRecoveryCheck()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_compute_recovery_check(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Decrypt a `name_encrypted` envelope using the handle's master key.
     */
open func decryptName(fileId: String, nameEncrypted: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_decrypt_name(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(fileId),
        FfiConverterString.lower(nameEncrypted),$0
    )
})
}
    
    /**
     * Decrypt a `name_encrypted` envelope and return both filename and MIME type.
     */
open func decryptNameWithMime(fileId: String, nameEncrypted: String)throws  -> DecryptedNameWithMime  {
    return try  FfiConverterTypeDecryptedNameWithMime_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_decrypt_name_with_mime(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(fileId),
        FfiConverterString.lower(nameEncrypted),$0
    )
})
}
    
    /**
     * Derive a FileKeyHandle for the given file ID.
     */
open func deriveFileKey(fileId: Data)throws  -> FileKeyHandle  {
    return try  FfiConverterTypeFileKeyHandle_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_derive_file_key(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(fileId),$0
    )
})
}
    
    /**
     * Derive the X25519 secret scalar from the master key. Returns 32 bytes.
     */
open func deriveX25519Private()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_derive_x25519_private(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Encrypt a filename + optional MIME type using the handle's master key.
     */
open func encryptName(fileId: String, filename: String, mimeType: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_encrypt_name(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(fileId),
        FfiConverterString.lower(filename),
        FfiConverterOptionString.lower(mimeType),$0
    )
})
}
    
    /**
     * Export the raw 32-byte key for writing to the OS keychain.
     * Only call this once at account setup; never log or transmit the result.
     */
open func exportForKeychain()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_method_masterkeyhandle_export_for_keychain(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMasterKeyHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MasterKeyHandle

    public static func lift(_ handle: UInt64) throws -> MasterKeyHandle {
        return MasterKeyHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MasterKeyHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MasterKeyHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MasterKeyHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMasterKeyHandle_lift(_ handle: UInt64) throws -> MasterKeyHandle {
    return try FfiConverterTypeMasterKeyHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMasterKeyHandle_lower(_ value: MasterKeyHandle) -> UInt64 {
    return FfiConverterTypeMasterKeyHandle.lower(value)
}




public struct ConstellationEdgeDto: Equatable, Hashable {
    public var fromIdx: UInt32
    public var toIdx: UInt32
    public var weight: Float
    public var flowSpeed: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fromIdx: UInt32, toIdx: UInt32, weight: Float, flowSpeed: Float) {
        self.fromIdx = fromIdx
        self.toIdx = toIdx
        self.weight = weight
        self.flowSpeed = flowSpeed
    }

    

    
}

#if compiler(>=6)
extension ConstellationEdgeDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConstellationEdgeDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConstellationEdgeDto {
        return
            try ConstellationEdgeDto(
                fromIdx: FfiConverterUInt32.read(from: &buf), 
                toIdx: FfiConverterUInt32.read(from: &buf), 
                weight: FfiConverterFloat.read(from: &buf), 
                flowSpeed: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: ConstellationEdgeDto, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.fromIdx, into: &buf)
        FfiConverterUInt32.write(value.toIdx, into: &buf)
        FfiConverterFloat.write(value.weight, into: &buf)
        FfiConverterFloat.write(value.flowSpeed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationEdgeDto_lift(_ buf: RustBuffer) throws -> ConstellationEdgeDto {
    return try FfiConverterTypeConstellationEdgeDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationEdgeDto_lower(_ value: ConstellationEdgeDto) -> RustBuffer {
    return FfiConverterTypeConstellationEdgeDto.lower(value)
}


public struct ConstellationFrameDto: Equatable, Hashable {
    public var frameIndex: UInt32
    public var seed: UInt64
    public var nodes: [ConstellationNodeDto]
    public var edges: [ConstellationEdgeDto]
    public var ringPhase: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(frameIndex: UInt32, seed: UInt64, nodes: [ConstellationNodeDto], edges: [ConstellationEdgeDto], ringPhase: Float) {
        self.frameIndex = frameIndex
        self.seed = seed
        self.nodes = nodes
        self.edges = edges
        self.ringPhase = ringPhase
    }

    

    
}

#if compiler(>=6)
extension ConstellationFrameDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConstellationFrameDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConstellationFrameDto {
        return
            try ConstellationFrameDto(
                frameIndex: FfiConverterUInt32.read(from: &buf), 
                seed: FfiConverterUInt64.read(from: &buf), 
                nodes: FfiConverterSequenceTypeConstellationNodeDto.read(from: &buf), 
                edges: FfiConverterSequenceTypeConstellationEdgeDto.read(from: &buf), 
                ringPhase: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: ConstellationFrameDto, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.frameIndex, into: &buf)
        FfiConverterUInt64.write(value.seed, into: &buf)
        FfiConverterSequenceTypeConstellationNodeDto.write(value.nodes, into: &buf)
        FfiConverterSequenceTypeConstellationEdgeDto.write(value.edges, into: &buf)
        FfiConverterFloat.write(value.ringPhase, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationFrameDto_lift(_ buf: RustBuffer) throws -> ConstellationFrameDto {
    return try FfiConverterTypeConstellationFrameDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationFrameDto_lower(_ value: ConstellationFrameDto) -> RustBuffer {
    return FfiConverterTypeConstellationFrameDto.lower(value)
}


public struct ConstellationNodeDto: Equatable, Hashable {
    public var kind: UInt8
    public var x: Float
    public var y: Float
    public var z: Float
    public var brightness: Float
    public var pulsePhase: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: UInt8, x: Float, y: Float, z: Float, brightness: Float, pulsePhase: Float) {
        self.kind = kind
        self.x = x
        self.y = y
        self.z = z
        self.brightness = brightness
        self.pulsePhase = pulsePhase
    }

    

    
}

#if compiler(>=6)
extension ConstellationNodeDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConstellationNodeDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConstellationNodeDto {
        return
            try ConstellationNodeDto(
                kind: FfiConverterUInt8.read(from: &buf), 
                x: FfiConverterFloat.read(from: &buf), 
                y: FfiConverterFloat.read(from: &buf), 
                z: FfiConverterFloat.read(from: &buf), 
                brightness: FfiConverterFloat.read(from: &buf), 
                pulsePhase: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: ConstellationNodeDto, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.kind, into: &buf)
        FfiConverterFloat.write(value.x, into: &buf)
        FfiConverterFloat.write(value.y, into: &buf)
        FfiConverterFloat.write(value.z, into: &buf)
        FfiConverterFloat.write(value.brightness, into: &buf)
        FfiConverterFloat.write(value.pulsePhase, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationNodeDto_lift(_ buf: RustBuffer) throws -> ConstellationNodeDto {
    return try FfiConverterTypeConstellationNodeDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationNodeDto_lower(_ value: ConstellationNodeDto) -> RustBuffer {
    return FfiConverterTypeConstellationNodeDto.lower(value)
}


public struct ConstellationPayloadDto: Equatable, Hashable {
    public var sessionId: Data
    public var ephemeralPubkey: Data
    public var nonce: Data
    public var expiresAtUnixMs: UInt64
    public var confirmCodeHash: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sessionId: Data, ephemeralPubkey: Data, nonce: Data, expiresAtUnixMs: UInt64, confirmCodeHash: Data) {
        self.sessionId = sessionId
        self.ephemeralPubkey = ephemeralPubkey
        self.nonce = nonce
        self.expiresAtUnixMs = expiresAtUnixMs
        self.confirmCodeHash = confirmCodeHash
    }

    

    
}

#if compiler(>=6)
extension ConstellationPayloadDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConstellationPayloadDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConstellationPayloadDto {
        return
            try ConstellationPayloadDto(
                sessionId: FfiConverterData.read(from: &buf), 
                ephemeralPubkey: FfiConverterData.read(from: &buf), 
                nonce: FfiConverterData.read(from: &buf), 
                expiresAtUnixMs: FfiConverterUInt64.read(from: &buf), 
                confirmCodeHash: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ConstellationPayloadDto, into buf: inout [UInt8]) {
        FfiConverterData.write(value.sessionId, into: &buf)
        FfiConverterData.write(value.ephemeralPubkey, into: &buf)
        FfiConverterData.write(value.nonce, into: &buf)
        FfiConverterUInt64.write(value.expiresAtUnixMs, into: &buf)
        FfiConverterData.write(value.confirmCodeHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationPayloadDto_lift(_ buf: RustBuffer) throws -> ConstellationPayloadDto {
    return try FfiConverterTypeConstellationPayloadDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationPayloadDto_lower(_ value: ConstellationPayloadDto) -> RustBuffer {
    return FfiConverterTypeConstellationPayloadDto.lower(value)
}


public struct ConstellationSessionInitDto: Equatable, Hashable {
    public var payload: ConstellationPayloadDto
    public var confirmCode: String
    public var ephemeralPrivate: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(payload: ConstellationPayloadDto, confirmCode: String, ephemeralPrivate: Data) {
        self.payload = payload
        self.confirmCode = confirmCode
        self.ephemeralPrivate = ephemeralPrivate
    }

    

    
}

#if compiler(>=6)
extension ConstellationSessionInitDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConstellationSessionInitDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConstellationSessionInitDto {
        return
            try ConstellationSessionInitDto(
                payload: FfiConverterTypeConstellationPayloadDto.read(from: &buf), 
                confirmCode: FfiConverterString.read(from: &buf), 
                ephemeralPrivate: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ConstellationSessionInitDto, into buf: inout [UInt8]) {
        FfiConverterTypeConstellationPayloadDto.write(value.payload, into: &buf)
        FfiConverterString.write(value.confirmCode, into: &buf)
        FfiConverterData.write(value.ephemeralPrivate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationSessionInitDto_lift(_ buf: RustBuffer) throws -> ConstellationSessionInitDto {
    return try FfiConverterTypeConstellationSessionInitDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConstellationSessionInitDto_lower(_ value: ConstellationSessionInitDto) -> RustBuffer {
    return FfiConverterTypeConstellationSessionInitDto.lower(value)
}


/**
 * Result of decrypting a name_encrypted blob with MIME type.
 */
public struct DecryptedNameWithMime: Equatable, Hashable {
    public var name: String
    public var mimeType: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, mimeType: String?) {
        self.name = name
        self.mimeType = mimeType
    }

    

    
}

#if compiler(>=6)
extension DecryptedNameWithMime: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecryptedNameWithMime: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecryptedNameWithMime {
        return
            try DecryptedNameWithMime(
                name: FfiConverterString.read(from: &buf), 
                mimeType: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: DecryptedNameWithMime, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.mimeType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptedNameWithMime_lift(_ buf: RustBuffer) throws -> DecryptedNameWithMime {
    return try FfiConverterTypeDecryptedNameWithMime.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptedNameWithMime_lower(_ value: DecryptedNameWithMime) -> RustBuffer {
    return FfiConverterTypeDecryptedNameWithMime.lower(value)
}


/**
 * Result of encrypting a chunk or metadata. Contains the cipher suite
 * identifier, a random nonce, and the ciphertext (including the GCM tag).
 */
public struct EncryptedData: Equatable, Hashable {
    public var cipherSuite: String
    public var nonce: Data
    public var ciphertext: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cipherSuite: String, nonce: Data, ciphertext: Data) {
        self.cipherSuite = cipherSuite
        self.nonce = nonce
        self.ciphertext = ciphertext
    }

    

    
}

#if compiler(>=6)
extension EncryptedData: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedData {
        return
            try EncryptedData(
                cipherSuite: FfiConverterString.read(from: &buf), 
                nonce: FfiConverterData.read(from: &buf), 
                ciphertext: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedData, into buf: inout [UInt8]) {
        FfiConverterString.write(value.cipherSuite, into: &buf)
        FfiConverterData.write(value.nonce, into: &buf)
        FfiConverterData.write(value.ciphertext, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedData_lift(_ buf: RustBuffer) throws -> EncryptedData {
    return try FfiConverterTypeEncryptedData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedData_lower(_ value: EncryptedData) -> RustBuffer {
    return FfiConverterTypeEncryptedData.lower(value)
}


/**
 * Master key bytes returned from `derive_master_key`.
 */
public struct MasterKeyResult: Equatable, Hashable {
    public var key: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: Data) {
        self.key = key
    }

    

    
}

#if compiler(>=6)
extension MasterKeyResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMasterKeyResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MasterKeyResult {
        return
            try MasterKeyResult(
                key: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: MasterKeyResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.key, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMasterKeyResult_lift(_ buf: RustBuffer) throws -> MasterKeyResult {
    return try FfiConverterTypeMasterKeyResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMasterKeyResult_lower(_ value: MasterKeyResult) -> RustBuffer {
    return FfiConverterTypeMasterKeyResult.lower(value)
}


public struct ObservedNodeDto: Equatable, Hashable {
    public var idx: UInt32
    public var brightness: Float
    public var confidence: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(idx: UInt32, brightness: Float, confidence: Float) {
        self.idx = idx
        self.brightness = brightness
        self.confidence = confidence
    }

    

    
}

#if compiler(>=6)
extension ObservedNodeDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeObservedNodeDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ObservedNodeDto {
        return
            try ObservedNodeDto(
                idx: FfiConverterUInt32.read(from: &buf), 
                brightness: FfiConverterFloat.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: ObservedNodeDto, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.idx, into: &buf)
        FfiConverterFloat.write(value.brightness, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeObservedNodeDto_lift(_ buf: RustBuffer) throws -> ObservedNodeDto {
    return try FfiConverterTypeObservedNodeDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeObservedNodeDto_lower(_ value: ObservedNodeDto) -> RustBuffer {
    return FfiConverterTypeObservedNodeDto.lower(value)
}


/**
 * Result of finishing an OPAQUE client login.
 */
public struct OpaqueLoginFinishResult: Equatable, Hashable {
    public var message: Data
    public var sessionKey: Data
    public var exportKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(message: Data, sessionKey: Data, exportKey: Data) {
        self.message = message
        self.sessionKey = sessionKey
        self.exportKey = exportKey
    }

    

    
}

#if compiler(>=6)
extension OpaqueLoginFinishResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOpaqueLoginFinishResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OpaqueLoginFinishResult {
        return
            try OpaqueLoginFinishResult(
                message: FfiConverterData.read(from: &buf), 
                sessionKey: FfiConverterData.read(from: &buf), 
                exportKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: OpaqueLoginFinishResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.message, into: &buf)
        FfiConverterData.write(value.sessionKey, into: &buf)
        FfiConverterData.write(value.exportKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpaqueLoginFinishResult_lift(_ buf: RustBuffer) throws -> OpaqueLoginFinishResult {
    return try FfiConverterTypeOpaqueLoginFinishResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpaqueLoginFinishResult_lower(_ value: OpaqueLoginFinishResult) -> RustBuffer {
    return FfiConverterTypeOpaqueLoginFinishResult.lower(value)
}


/**
 * Result of starting an OPAQUE registration or login.
 */
public struct OpaqueStartResult: Equatable, Hashable {
    public var message: Data
    public var state: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(message: Data, state: Data) {
        self.message = message
        self.state = state
    }

    

    
}

#if compiler(>=6)
extension OpaqueStartResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOpaqueStartResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OpaqueStartResult {
        return
            try OpaqueStartResult(
                message: FfiConverterData.read(from: &buf), 
                state: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: OpaqueStartResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.message, into: &buf)
        FfiConverterData.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpaqueStartResult_lift(_ buf: RustBuffer) throws -> OpaqueStartResult {
    return try FfiConverterTypeOpaqueStartResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpaqueStartResult_lower(_ value: OpaqueStartResult) -> RustBuffer {
    return FfiConverterTypeOpaqueStartResult.lower(value)
}


/**
 * Result of generating a recovery phrase.
 */
public struct RecoveryPhraseResult: Equatable, Hashable {
    public var phrase: String
    public var masterKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(phrase: String, masterKey: Data) {
        self.phrase = phrase
        self.masterKey = masterKey
    }

    

    
}

#if compiler(>=6)
extension RecoveryPhraseResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecoveryPhraseResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecoveryPhraseResult {
        return
            try RecoveryPhraseResult(
                phrase: FfiConverterString.read(from: &buf), 
                masterKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: RecoveryPhraseResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.phrase, into: &buf)
        FfiConverterData.write(value.masterKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecoveryPhraseResult_lift(_ buf: RustBuffer) throws -> RecoveryPhraseResult {
    return try FfiConverterTypeRecoveryPhraseResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecoveryPhraseResult_lower(_ value: RecoveryPhraseResult) -> RustBuffer {
    return FfiConverterTypeRecoveryPhraseResult.lower(value)
}


public enum CryptoError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Encryption(detail: String
    )
    case Decryption
    case Kdf(detail: String
    )
    case InvalidRecoveryPhrase
    case InvalidInput(detail: String
    )
    case Opaque(detail: String
    )
    case Cancelled
    case Io(detail: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CryptoError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Encryption(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Decryption
        case 3: return .Kdf(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidRecoveryPhrase
        case 5: return .InvalidInput(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Opaque(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 7: return .Cancelled
        case 8: return .Io(
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Encryption(detail):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(detail, into: &buf)
            
        
        case .Decryption:
            writeInt(&buf, Int32(2))
        
        
        case let .Kdf(detail):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(detail, into: &buf)
            
        
        case .InvalidRecoveryPhrase:
            writeInt(&buf, Int32(4))
        
        
        case let .InvalidInput(detail):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Opaque(detail):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(detail, into: &buf)
            
        
        case .Cancelled:
            writeInt(&buf, Int32(7))
        
        
        case let .Io(detail):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCryptoError_lift(_ buf: RustBuffer) throws -> CryptoError {
    return try FfiConverterTypeCryptoError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCryptoError_lower(_ value: CryptoError) -> RustBuffer {
    return FfiConverterTypeCryptoError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeConstellationPayloadDto: FfiConverterRustBuffer {
    typealias SwiftType = ConstellationPayloadDto?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeConstellationPayloadDto.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeConstellationPayloadDto.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeConstellationEdgeDto: FfiConverterRustBuffer {
    typealias SwiftType = [ConstellationEdgeDto]

    public static func write(_ value: [ConstellationEdgeDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConstellationEdgeDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ConstellationEdgeDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [ConstellationEdgeDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConstellationEdgeDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeConstellationNodeDto: FfiConverterRustBuffer {
    typealias SwiftType = [ConstellationNodeDto]

    public static func write(_ value: [ConstellationNodeDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConstellationNodeDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ConstellationNodeDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [ConstellationNodeDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConstellationNodeDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeObservedNodeDto: FfiConverterRustBuffer {
    typealias SwiftType = [ObservedNodeDto]

    public static func write(_ value: [ObservedNodeDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeObservedNodeDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ObservedNodeDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [ObservedNodeDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeObservedNodeDto.read(from: &buf))
        }
        return seq
    }
}
/**
 * Compute a recovery check value from a master key. Returns 32-byte check value.
 * This is stored server-side so we can verify a recovery phrase produces the
 * correct master key.
 */
public func computeRecoveryCheck(masterKey: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_compute_recovery_check(
        FfiConverterData.lower(masterKey),$0
    )
})
}
/**
 * Encode `payload` into the visualisation frame at `frame_index`.
 */
public func constellationEncode(payload: ConstellationPayloadDto, frameIndex: UInt32)throws  -> ConstellationFrameDto  {
    return try  FfiConverterTypeConstellationFrameDto_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_constellation_encode(
        FfiConverterTypeConstellationPayloadDto_lower(payload),
        FfiConverterUInt32.lower(frameIndex),$0
    )
})
}
/**
 * Generate a fresh pairing session (display side).
 */
public func constellationNewSession(expiresInSecs: UInt32) -> ConstellationSessionInitDto  {
    return try!  FfiConverterTypeConstellationSessionInitDto_lift(try! rustCall() {
    uniffi_beebeeb_uniffi_fn_func_constellation_new_session(
        FfiConverterUInt32.lower(expiresInSecs),$0
    )
})
}
/**
 * Constant-time verify a 6-digit code against a payload.
 */
public func constellationVerifyCode(payload: ConstellationPayloadDto, code: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_beebeeb_uniffi_fn_func_constellation_verify_code(
        FfiConverterTypeConstellationPayloadDto_lower(payload),
        FfiConverterString.lower(code),$0
    )
})
}
/**
 * Decrypt a ciphertext chunk that was produced by `encrypt_chunk`.
 */
public func decryptChunk(key: Data, nonce: Data, ciphertext: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_decrypt_chunk(
        FfiConverterData.lower(key),
        FfiConverterData.lower(nonce),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
/**
 * Decrypt a metadata blob back to a UTF-8 string.
 */
public func decryptMetadata(key: Data, nonce: Data, ciphertext: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_decrypt_metadata(
        FfiConverterData.lower(key),
        FfiConverterData.lower(nonce),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
/**
 * Decrypt a `name_encrypted` JSON envelope back to a plaintext filename.
 * Handles both new format (`{"name":"...","mime_type":"..."}`) and legacy bare strings.
 */
public func decryptName(masterKey: Data, fileId: String, nameEncrypted: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_decrypt_name(
        FfiConverterData.lower(masterKey),
        FfiConverterString.lower(fileId),
        FfiConverterString.lower(nameEncrypted),$0
    )
})
}
/**
 * Decrypt a `name_encrypted` JSON envelope and return both the filename and
 * the MIME type (if present in the encrypted payload).
 */
public func decryptNameWithMime(masterKey: Data, fileId: String, nameEncrypted: String)throws  -> DecryptedNameWithMime  {
    return try  FfiConverterTypeDecryptedNameWithMime_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_decrypt_name_with_mime(
        FfiConverterData.lower(masterKey),
        FfiConverterString.lower(fileId),
        FfiConverterString.lower(nameEncrypted),$0
    )
})
}
/**
 * Derive a per-file encryption key from a master key and file ID via
 * HKDF-SHA256. Returns the 32-byte file key.
 */
public func deriveFileKey(masterKey: Data, fileId: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_derive_file_key(
        FfiConverterData.lower(masterKey),
        FfiConverterData.lower(fileId),$0
    )
})
}
/**
 * Derive a 32-byte master key from a password and salt (>= 16 bytes) via
 * Argon2id. Returns the key bytes.
 */
public func deriveMasterKey(password: String, salt: Data)throws  -> MasterKeyResult  {
    return try  FfiConverterTypeMasterKeyResult_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_derive_master_key(
        FfiConverterString.lower(password),
        FfiConverterData.lower(salt),$0
    )
})
}
/**
 * Derive a share key from a shared secret and file ID. Returns 32-byte share key.
 */
public func deriveShareKey(sharedSecret: Data, fileId: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_derive_share_key(
        FfiConverterData.lower(sharedSecret),
        FfiConverterData.lower(fileId),$0
    )
})
}
/**
 * Derive an X25519 secret scalar from a master key. Returns 32 bytes.
 */
public func deriveX25519Private(masterKey: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_derive_x25519_private(
        FfiConverterData.lower(masterKey),$0
    )
})
}
/**
 * Derive an X25519 public point from a secret scalar. Returns 32 bytes.
 */
public func deriveX25519Public(privateKey: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_derive_x25519_public(
        FfiConverterData.lower(privateKey),$0
    )
})
}
/**
 * Encrypt a plaintext chunk with AES-256-GCM. Returns the encrypted data
 * containing cipher suite, nonce, and ciphertext.
 */
public func encryptChunk(key: Data, plaintext: Data)throws  -> EncryptedData  {
    return try  FfiConverterTypeEncryptedData_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_encrypt_chunk(
        FfiConverterData.lower(key),
        FfiConverterData.lower(plaintext),$0
    )
})
}
/**
 * Encrypt a UTF-8 metadata string (filename, path, etc.) with AES-256-GCM.
 */
public func encryptMetadata(key: Data, metadata: String)throws  -> EncryptedData  {
    return try  FfiConverterTypeEncryptedData_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_encrypt_metadata(
        FfiConverterData.lower(key),
        FfiConverterString.lower(metadata),$0
    )
})
}
/**
 * Encrypt a filename + optional MIME type into the canonical JSON envelope.
 * The result is a JSON string containing cipher_suite, nonce, and ciphertext.
 */
public func encryptName(masterKey: Data, fileId: String, filename: String, mimeType: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_encrypt_name(
        FfiConverterData.lower(masterKey),
        FfiConverterString.lower(fileId),
        FfiConverterString.lower(filename),
        FfiConverterOptionString.lower(mimeType),$0
    )
})
}
/**
 * Generate a new 12-word BIP39 recovery phrase and the corresponding master
 * key. The phrase IS the master secret.
 */
public func generateRecoveryPhrase()throws  -> RecoveryPhraseResult  {
    return try  FfiConverterTypeRecoveryPhraseResult_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_generate_recovery_phrase($0
    )
})
}
/**
 * Guess the MIME type from a filename extension.
 * Returns `None` for unknown extensions.
 */
public func guessMimeType(filename: String) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_beebeeb_uniffi_fn_func_guess_mime_type(
        FfiConverterString.lower(filename),$0
    )
})
}
/**
 * Returns `true` if the given MIME type represents media (image or video).
 * Single source of truth for all clients.
 */
public func isMedia(mimeType: String?) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_beebeeb_uniffi_fn_func_is_media(
        FfiConverterOptionString.lower(mimeType),$0
    )
})
}
/**
 * Finish OPAQUE client login. Returns the finalization message, the session
 * key, and the export key (used to derive the master key envelope).
 */
public func opaqueLoginFinish(clientState: Data, password: Data, serverResponse: Data)throws  -> OpaqueLoginFinishResult  {
    return try  FfiConverterTypeOpaqueLoginFinishResult_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_opaque_login_finish(
        FfiConverterData.lower(clientState),
        FfiConverterData.lower(password),
        FfiConverterData.lower(serverResponse),$0
    )
})
}
/**
 * Start OPAQUE client login. Returns the login message and client state.
 */
public func opaqueLoginStart(password: Data)throws  -> OpaqueStartResult  {
    return try  FfiConverterTypeOpaqueStartResult_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_opaque_login_start(
        FfiConverterData.lower(password),$0
    )
})
}
/**
 * Finish OPAQUE client registration. Takes the client state from the start
 * step, the password, and the server's response. Returns the registration
 * upload bytes to send to the server.
 */
public func opaqueRegistrationFinish(clientState: Data, password: Data, serverResponse: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_opaque_registration_finish(
        FfiConverterData.lower(clientState),
        FfiConverterData.lower(password),
        FfiConverterData.lower(serverResponse),$0
    )
})
}
/**
 * Start OPAQUE client registration. Returns the registration message and
 * client state (both needed for the finish step).
 */
public func opaqueRegistrationStart(password: Data)throws  -> OpaqueStartResult  {
    return try  FfiConverterTypeOpaqueStartResult_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_opaque_registration_start(
        FfiConverterData.lower(password),$0
    )
})
}
/**
 * Recover a master key from a 12-word BIP39 recovery phrase.
 * Returns the 32-byte master key.
 */
public func recoverFromPhrase(phrase: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_recover_from_phrase(
        FfiConverterString.lower(phrase),$0
    )
})
}
/**
 * Compute an X25519 shared secret from my secret scalar and their public point.
 * Returns 32-byte shared secret.
 */
public func x25519SharedSecret(myPrivate: Data, theirPublic: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_beebeeb_uniffi_fn_func_x25519_shared_secret(
        FfiConverterData.lower(myPrivate),
        FfiConverterData.lower(theirPublic),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_beebeeb_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_compute_recovery_check() != 28278) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_constellation_encode() != 55630) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_constellation_new_session() != 21938) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_constellation_verify_code() != 40191) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_decrypt_chunk() != 1418) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_decrypt_metadata() != 59510) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_decrypt_name() != 9592) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_decrypt_name_with_mime() != 47898) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_derive_file_key() != 7047) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_derive_master_key() != 58065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_derive_share_key() != 10175) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_derive_x25519_private() != 64443) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_derive_x25519_public() != 3860) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_encrypt_chunk() != 23692) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_encrypt_metadata() != 360) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_encrypt_name() != 54015) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_generate_recovery_phrase() != 56821) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_guess_mime_type() != 41583) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_is_media() != 46056) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_opaque_login_finish() != 15751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_opaque_login_start() != 19878) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_opaque_registration_finish() != 42222) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_opaque_registration_start() != 35428) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_recover_from_phrase() != 25900) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_func_x25519_shared_secret() != 52845) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_constellationdecoderhandle_frames_ingested() != 10893) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_constellationdecoderhandle_ingest_frame() != 7606) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_constellationdecoderhandle_progress() != 18899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_constellationdecoderhandle_reset() != 57183) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_constellationdecoderhandle_shards_collected() != 56364) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_decrypt_chunk() != 50441) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_decrypt_metadata() != 41867) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_encrypt_chunk() != 10384) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_filekeyhandle_encrypt_metadata() != 60336) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_compute_recovery_check() != 4155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_decrypt_name() != 40318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_decrypt_name_with_mime() != 23459) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_derive_file_key() != 1679) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_derive_x25519_private() != 61634) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_encrypt_name() != 53513) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_method_masterkeyhandle_export_for_keychain() != 50366) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_constructor_constellationdecoderhandle_new() != 21598) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_constructor_masterkeyhandle_from_keychain_bytes() != 25584) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_beebeeb_uniffi_checksum_constructor_masterkeyhandle_from_recovery_phrase() != 63639) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBeebeebUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all