#!/usr/bin/env bash
# Vendor three.js so the constellation WebView stops fetching script from a US
# CDN (unpkg). Emits a base64 module that is inlined as a data: URL — no new
# runtime dependency, no metro asset config, and no escaping hazard from
# minified source. Pin moves are a reviewed diff of the .ts file.
set -euo pipefail
VERSION="0.158.0"
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/src/lib/vendor/three-min-b64.ts"
TMP="$(mktemp)"; trap 'rm -f "$TMP"' EXIT
curl -fsSL "https://registry.npmjs.org/three/-/three-${VERSION}.tgz" -o "$TMP"
mkdir -p "$(dirname "$OUT")"
{
  printf '// GENERATED by scripts/vendor-three.sh — do not edit.\n'
  printf '// three.js v%s, base64, inlined into the constellation WebView as a\n' "$VERSION"
  printf '// data: URL so no third-party CDN is in the app path.\n'
  printf 'export const THREE_VERSION = %s\n' "'$VERSION'"
  printf 'export const THREE_MIN_JS_B64 =\n  %s\n' "'$(tar -xzOf "$TMP" package/build/three.min.js | base64 | tr -d '\n')'"
} > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
